/* ============================================================
   FACT CHECKS — edita, borra o agrega líneas.
   Usa {nombre} si quieres que ponga su nombre.
   No hace falta escribir "Fact check:" (se agrega solo).
   ============================================================ */
window.FACT_CHECKS = [
  "Eres una persona increíble y este día no te define.",
  "{nombre}, un mal día no es una mala vida.",
  "Estás cansada, no rota.",
  "El día pecó. Tú no.",
  "Mereces agua, un snack y que nadie te pida una sonrisa.",
  "No tienes que ser productiva para merecer descanso.",
  "Esto que sientes es válido. También se va a ir.",
  "Ya sobreviviste días peores. Este también se va a aburrir.",
  "No eres dramática. Estás llena. Hay diferencia.",
  "Tu valor no baja porque hoy no te salió nada.",
  "{nombre} sigue siendo {nombre}, aunque el martes se haya portado mal.",
  "Nadie te está calificando. Ni siquiera tú deberías.",
  "Hacer menos hoy no te hace menos.",
  "Si el día fuera un examen, hoy era de práctica. No cuenta.",
  "Está bien no tener una respuesta linda.",
  "Te puedes echar a perder un rato. No se te caduca el ticket de ser querida.",
  "Un mal rato no es tu personalidad.",
  "Descansar también es una forma de arreglarlo.",
  "No tienes que contarlo bien. Solo tienes que llegar a la cama.",
  "Eres más constante que este día. Él se acaba. Tú no.",
  "Nadie gana un miércoles a la fuerza.",
  "Si hoy solo te lavaste la cara, ya fue un logro de infraestructura.",
  "No estás atrasada. Estás viva en un día pesado.",
  "Lo que no alcanzaste no te está esperando con un palo.",
  "{nombre}, esto no es un veredicto. Es clima.",
  "Puedes ser suave contigo y seguir siendo fuerte. No es trampa.",
  "El mundo puede esperar 20 minutos. Tú no tienes que esperar a sentirte mejor para tratarte bien.",
  "No todo lo que duele es una señal. A veces es hambre o sueño.",
  "Eres alguien a quien le importan las cosas. Eso cansa. También habla bien de ti.",
  "Hoy no tienes que inspirar a nadie.",
  "Si te escondieras un rato, el universo no te despedirían.",
  "Hay permiso oficial para no estar “de buenas”.",
  "Tu día feo no cancela tus días buenos. Solo los pausa.",
  "No estás fallando. Estás procesando.",
  "Una persona increíble también se sienta a mirar el techo. Ciencia.",
  "Si alguien te viera ahora y te conociera de verdad, no te bajaría el puntaje.",
  "{nombre}, te creo. Aunque no lo hayas explicado.",
  "No tienes que convertirlo en aprendizaje hoy. Mañana, si acaso.",
  "Está permitido pedir algo dulce sin justificar el día.",
  "Eres de las que sigue. Aunque hoy sea a paso de cuchara.",
  "Este día no tiene la última palabra sobre ti.",
  "La gente soportable incluye a {nombre}. Sobre todo a {nombre}.",
  "No estás “mucho”. El día está corto de paciencia.",
  "Si fuera fácil, no se llamaría día feo. Se llamaría martes.",
  "Mereces el mismo tono de voz que le pondrías a alguien que quieres.",
  "Nada de esto te hace pesada. Te hace humana con batería al 12%.",
  "Puedes cerrar la laptop emocional. No hay guardia nocturna.",
  "Hoy no se trata de brillar. Se trata de no apagarte del todo. Ya vas bien.",
  "Si el ánimo no sube, igual tú no bajas de categoría.",
  "Eres una persona increíble los días que no se nota. Sobre todo esos.",
  "Lo que te pesa no te define. Cómo te cuidas un poco, sí.",
  "{nombre}, este shot no te arregla la vida. Solo te recuerda que no estás sola en el día.",
  "Facturado: mereces un rato tonto después de un rato serio.",
  "Si solo aguantaste, ya cumpliste la cuota.",
  "Nadie está tomando asistencia de tu alegría.",
];
